import { defineConfig } from 'vite-plus'
export default defineConfig({
  // Pre-commit checks, run by `vp staged` from `.vite-hooks/pre-commit`. These
  // reproduce the lint/format half of CI now that the workflows no longer run on
  // pushes to main (CI is a pre-merge gate only). `vp staged` runs each command
  // only when matching files are staged — the same "don't start an unrelated
  // job" behaviour as the CI `paths:` filters. The matching tests have no git
  // pre-push hook: they are the pusher's responsibility (`vp run test:changed`,
  // `./scripts/checks/rust.sh pre-push`), with a Claude hook
  // (.claude/hooks/push-test-reminder.mjs) reminding before a session's first push.
  staged: {
    // Format + lint + typecheck (mirrors the ci-typescript `vp check` step).
    '*': 'vp check --fix',
    // Markdown lint (mirrors the lint-markdown workflow).
    '*.md': 'vp run lint:docs',
    // Rust fmt + clippy, shared with ci-rust.yml / ci-rust-tauri.yml. fmt is
    // whole-workspace (compile-free); clippy is scoped to the crates changed vs
    // origin/main plus their dependents, so it stays light locally while CI
    // still runs the full --workspace. Self-skips when the toolchain (or the
    // Tauri GTK libs) is unavailable.
    '*.{rs,toml}': './scripts/checks/rust.sh pre-commit',
  },
  // Resolve workspace-package imports against their `source` export
  // condition (TS source) instead of the default-built dist. Each
  // package.json declares both: `{ "exports": { ".": { "source":
  // "./src/index.ts", "default": "./dist/index.js" } } }`. With this set,
  // `vp dev` / `vp build` / per-app builds skip the slice build step and
  // pick up source edits directly. Vitest projects mode loads each
  // per-package vite.config.ts independently, so the same `resolve.conditions`
  // is duplicated there — without it, tests would still pull from `dist`.
  //
  // Vitest runs test modules through Vite's SSR pipeline, which has its
  // own resolver — `ssr.resolve.conditions`. If only `resolve.conditions`
  // is set, the SSR resolver still picks `default` (the built `dist`),
  // turning every newly-added cross-package export into a runtime
  // `is not a function` error until somebody re-runs `vp pack`. Per-
  // package vite configs that test against workspace deps need BOTH —
  // see `slices/apps/apps-core/vite.config.ts` and
  // `slices/shared-structures/shared-structures-core/vite.config.ts`.
  resolve: {
    conditions: ['source'],
  },
  ssr: {
    resolve: { conditions: ['source'] },
  },
  test: {
    // Each Vitest package owns its own vite.config.ts; listing them as
    // projects lets `vp test` from the workspace root honor per-package
    // settings (e.g. `environment: 'jsdom'` in react-tundraish) instead of
    // running everything under a single root config.
    projects: [
      'apps/website/vite.config.ts',
      'apps/wildflower-react/vite.config.ts',
      'global/effect-messaging/effect-messaging-core/vite.config.ts',
      'global/effect-messaging/effect-messaging-react/vite.config.ts',
      'global/kitchen-sink/vite.config.ts',
      'global/react-kitchen-sink/vite.config.ts',
      'global/react-tundraish/vite.config.ts',
      'slices/**/vite.config.ts',
      '!slices/apps/self-hosted-apps/**',
      '!**/node_modules/**',
    ],
  },
  fmt: {
    trailingComma: 'es5',
    tabWidth: 2,
    semi: false,
    singleQuote: true,
    printWidth: 100,
    sortPackageJson: {
      sortScripts: true,
    },
    sortImports: {
      partitionByNewline: true,
      newlinesBetween: false,
    },
    ignorePatterns: [
      '.claude/**/*',
      // /design-sync authored preview compositions — converter scratch .tsx,
      // not project source (see the matching lint.ignorePatterns entry).
      '.design-sync/**/*',
      '**/tapes/**/*',
      '**/dist/**',
      '**/dist-html/**',
      '**/dist-embedded/**',
      '**/dist-web/**',
      '**/coverage/**',
      '**/vendor/**',
      '**/test/snapshots/**',
      '**/*.generated.ts',
      // Effect schemas generated from a service's OpenAPI spec
      // (`openapi-to-effect`); gitignored, reference-only.
      '**/http-api-definition/generated/**',
      // Rust manifests are owned by the Rust toolchain (`cargo fmt` formats
      // `.rs` only; Cargo.toml layout is hand-maintained). oxfmt's TOML rules
      // disagree with how they're written (e.g. collapsing multi-line feature
      // arrays), which would otherwise fail `vp check` — so skip all TOML.
      '**/*.toml',
      // Committed OpenAPI snapshot emitted by the Rust server
      // (`serde_json::to_string_pretty`, written by the `UPDATE_OPENAPI=1`
      // snapshot test). That test asserts byte-exact equality, but oxfmt would
      // collapse its short arrays onto one line and break the test on the next
      // `vp fmt` — so leave its formatting to the serde_json emitter.
      '**/openapi/*.openapi.json',
      '**/autogenerated/**/*',
      // `tauri-plugin`'s build script (with the `build` feature) re-emits the
      // ACL JSON schema next to each plugin's `permissions/` dir on every
      // cargo build. Hand-formatting it would just be re-clobbered.
      '**/permissions/schemas/*.json',
    ],
  },
  lint: {
    ignorePatterns: [
      '.claude/**/*',
      // /design-sync authored preview compositions. These are scratch .tsx
      // files compiled by the design-sync converter's own esbuild (it aliases
      // the `react-tundraish` import to a runtime global), not project source —
      // they intentionally use multiple named exports, no explicit return
      // types, and an unresolvable package import, none of which apply here.
      '.design-sync/**/*',
      '**/tapes/**/*',
      '**/dist/**',
      '**/dist-html/**',
      '**/dist-embedded/**',
      '**/dist-web/**',
      '**/coverage/**',
      '**/vendor/**',
      '**/test/snapshots/**',
      '**/*.generated.ts',
      // Effect schemas generated from a service's OpenAPI spec
      // (`openapi-to-effect`); gitignored, reference-only.
      '**/http-api-definition/generated/**',
    ],
    plugins: ['typescript', 'react', 'unicorn', 'import'],
    categories: {
      correctness: 'error',
      suspicious: 'error',
      // pedantic: "warn",
      // perf: "error",
      // style: "error",
      // restriction: "error",
    },
    env: {
      builtin: true,
      es2024: true,
    },
    options: {
      typeAware: true,
      typeCheck: true,
      reportUnusedDisableDirectives: 'error',
    },
    rules: {
      // Explicitly disabled rules
      'import/no-unassigned-import': 'off',
      'import/no-named-export': 'off',
      'unicorn/filename-case': 'off',
      '@typescript-eslint/no-unnecessary-type-arguments': 'off',
      '@typescript-eslint/no-namespace': 'off',
      'react/react-in-jsx-scope': 'off',
      'import/namespace': 'off',

      // Configured rules
      'eslint/no-underscore-dangle': ['error', { allow: ['_tag', '_count', '_pageToken'] }],
      'no-shadow': ['error', { allow: ['fc'] }],
      'import/max-dependencies': ['warn', { max: 15 }],
      '@typescript-eslint/no-empty-object-type': ['error', { allowInterfaces: 'always' }],
      'no-unused-vars': [
        'error',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
        },
      ],
      'react/only-export-components': [
        'error',
        {
          allowExportNames: [
            'loader',
            'clientLoader',
            'action',
            'clientAction',
            'ErrorBoundary',
            'HydrateFallback',
            'headers',
            'handle',
            'links',
            'meta',
            'shouldRevalidate',
          ],
        },
      ],

      // Extra rules
      '@typescript-eslint/no-unsafe-type-assertion': 'error',
      '@typescript-eslint/consistent-type-imports': 'error',
      '@typescript-eslint/no-explicit-any': 'error',
      '@typescript-eslint/no-unsafe-assignment': 'error',
      '@typescript-eslint/explicit-function-return-type': [
        'error',
        { allowIIFEs: true, allowExpressions: true },
      ],
      'unicorn/no-array-callback-reference': 'off',
      'react-hooks/rules-of-hooks': 'error',
      'react-hooks/exhaustive-deps': 'warn',
      'import/default': 'error',
      'import/no-named-as-default': 'warn',
      'import/no-named-as-default-member': 'warn',
      'import/no-duplicates': 'warn',

      // Enable-only rules (warnings — violations not yet fixed)
      'react/no-array-index-key': 'warn',
      'no-await-in-loop': 'warn',
      'no-deprecated': 'warn',
      'no-warning-comments': 'warn',
      'switch-exhaustiveness-check': 'warn',
      'no-void': ['error', { allowAsStatement: true }],
      'react/button-has-type': 'warn',
      'import/group-exports': 'warn',
      'react/jsx-curly-brace-presence': ['error', { propElementValues: 'always' }],
      'react/jsx-filename-extension': ['error', { extensions: ['.jsx', '.tsx'] }],
      'no-console': 'warn',
      'no-nested-ternary': 'warn',
    },
    overrides: [
      {
        files: ['**/src/routes/**/*.tsx'],
        rules: {
          'react/only-export-components': 'off',
        },
      },
      {
        files: ['**/*.ts', '**/*.tsx', '**/*.mts', '**/*.cts'],
        rules: {
          'no-var': 'error',
          'no-with': 'off',
          'prefer-const': 'error',
          'prefer-rest-params': 'error',
          'prefer-spread': 'error',
        },
      },
      {
        files: ['**/*.tsx'],
        rules: {
          'no-ternary': 'off',
        },
      },
    ],
  },
})
