/**
 * Shared esbuild bundler for the sniffer document-start bootstraps. Both
 * `build-tauri-bootstrap.mts` (desktop `WebviewWindow` path, `__TAURI__`) and
 * `build-native-bootstrap.mts` (mobile `tauri-plugin-native-webview` path,
 * bridge transport) call {@link buildBootstrap}; the esbuild config,
 * generated-TS template, and dual-output writing live here once.
 *
 * @remarks Each invocation writes two gitignored outputs (produced fresh on
 * every `vp install` via the package's `prepare` script):
 *   - `src/<outBaseName>.generated.ts` — a `string` const for the TS exports in
 *     `src/index.ts` (and the tests). Lives under `src/` so the resolver finds
 *     it under `customConditions: ['source']`.
 *   - `dist/<outBaseName>.js` — the raw IIFE the host injects (a Rust crate may
 *     also `include_str!` it).
 */

import { mkdirSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { build } from 'esbuild'

interface BuildBootstrapOptions {
  /** Package root — pass `resolve(import.meta.dirname, '..')` from the caller. */
  readonly pkgRoot: string
  /** Entry module under `src/`, e.g. `'tauri-sniffer-entry.ts'`. */
  readonly entryFile: string
  /** Exported const name in the generated `.ts`, e.g. `'tauriSnifferBootstrapScript'`. */
  readonly constName: string
  /** Output base name (no extension), e.g. `'tauri-bootstrap'`. */
  readonly outBaseName: string
  /** Calling script's filename, for the `@generated` header. */
  readonly scriptName: string
  /** Package script that regenerates this output, e.g. `'generate-tauri-bootstrap'`. */
  readonly regenerateScript: string
}

/**
 * Bundle `src/<entryFile>` into a self-contained IIFE and write both the
 * `string`-const TS module and the raw `dist` JS. Throws if esbuild produces no
 * output so a build misconfiguration fails loudly rather than emitting an empty
 * (silently no-op) bootstrap.
 */
const buildBootstrap = async (options: BuildBootstrapOptions): Promise<void> => {
  const { pkgRoot, entryFile, constName, outBaseName, scriptName, regenerateScript } = options

  const result = await build({
    entryPoints: [resolve(pkgRoot, 'src', entryFile)],
    bundle: true,
    format: 'iife',
    platform: 'browser',
    target: 'es2020',
    write: false,
    legalComments: 'none',
    minify: false,
    // Match the TS infra's `customConditions: ['source']`: workspace packages
    // export `./src/index.ts` under the `source` condition so consumers compile
    // from source without an intermediate build step.
    conditions: ['source'],
  })

  const output = result.outputFiles[0]
  if (output === undefined) {
    throw new Error(`${scriptName}: esbuild produced no output for src/${entryFile}`)
  }
  const code = output.text.trim()

  const generatedTs = `// @generated by scripts/${scriptName} — do not edit by hand.
// Regenerate with \`vp run ${regenerateScript}\` after changing ${entryFile} or
// any of its transitive imports. Gitignored — produced fresh on every
// \`vp install\` via the package's \`prepare\` script.

const ${constName}: string = ${JSON.stringify(code)}

export { ${constName} }
`

  const tsOutPath = resolve(pkgRoot, 'src', `${outBaseName}.generated.ts`)
  writeFileSync(tsOutPath, generatedTs, 'utf8')

  const distDir = resolve(pkgRoot, 'dist')
  mkdirSync(distDir, { recursive: true })
  const jsOutPath = resolve(distDir, `${outBaseName}.js`)
  writeFileSync(jsOutPath, code, 'utf8')

  // oxlint-disable-next-line no-console -- intentional build-step output
  console.log(`Wrote ${tsOutPath} and ${jsOutPath} (${code.length} chars)`)
}

export { buildBootstrap }
export type { BuildBootstrapOptions }
