// Build-time bundler for the Tauri sniffer bootstrap.
//
// Bundles `src/tauri-sniffer-entry.ts` (the shim + `installSniffer()`
// invocation) as a self-contained IIFE. Writes the result to two paths:
//   - `src/tauri-bootstrap.generated.ts` — `string` constant for the
//     TypeScript exports in `src/index.ts` (and the tests in `tests/`).
//     Lives under `src/` so the TS module resolver finds it under the
//     package's `customConditions: ['source']`.
//   - `dist/tauri-bootstrap.js` — raw IIFE that the Rust crate
//     `browser-sniffer-tauri-rust` includes via `include_str!`.
//
// Both outputs are gitignored. CI's `tauri` lint/test job runs
// `pnpm install` (which triggers this script via `prepare`) before
// `cargo build`/`cargo nextest`, so the latest bytes are always
// compiled in. Rust-only PRs that don't need a fresh bootstrap fall
// back to a stub written by the workflow, just so `include_str!`
// resolves at compile time.

import { mkdirSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { build } from 'esbuild'

// `import.meta.dirname` is a string by spec (Node 20.11+).
const pkgRoot = resolve(import.meta.dirname, '..')

const result = await build({
  entryPoints: [resolve(pkgRoot, 'src/tauri-sniffer-entry.ts')],
  bundle: true,
  format: 'iife',
  platform: 'browser',
  target: 'es2020',
  write: false,
  legalComments: 'none',
  minify: false,
  // Match the TS infra's `customConditions: ['source']` in
  // tsconfig.json: workspace packages export `./src/index.ts` under the
  // `source` condition so consumers compile from source without an
  // intermediate build step. Without this, esbuild resolves
  // `browser-sniffer-injected` to its (unbuilt) `dist/index.js`.
  conditions: ['source'],
})

const code = result.outputFiles[0].text.trim()

const generatedTs = `// @generated by scripts/build-tauri-bootstrap.mts — do not edit by hand.
// Regenerate with \`vp run generate-tauri-bootstrap\` after changing
// tauri-sniffer-entry.ts or any of its transitive imports (including
// the sniffer body in browser-sniffer-injected). Gitignored — produced
// fresh on every \`vp install\` via the package's \`prepare\` script.

const tauriSnifferBootstrapScript: string = ${JSON.stringify(code)}

export { tauriSnifferBootstrapScript }
`

const tsOutPath = resolve(pkgRoot, 'src/tauri-bootstrap.generated.ts')
writeFileSync(tsOutPath, generatedTs, 'utf8')

const distDir = resolve(pkgRoot, 'dist')
mkdirSync(distDir, { recursive: true })
const jsOutPath = resolve(distDir, 'tauri-bootstrap.js')
writeFileSync(jsOutPath, code, 'utf8')

// oxlint-disable-next-line no-console -- intentional build-step output
console.log(`Wrote ${tsOutPath} and ${jsOutPath} (${code.length} chars)`)
