// Build-time bundler for the NATIVE sniffer bootstrap (iOS WKWebView / Android
// WebView popups opened by `tauri-plugin-native-webview`).
//
// Mirrors `build-tauri-bootstrap.mts` but bundles `src/native-sniffer-entry.ts`
// (the bridge-backed transport — no `__TAURI__`, no BrowserTopBar). Writes:
//   - `src/native-bootstrap.generated.ts` — `string` constant for the TS
//     exports in `src/index.ts` (and the tests in `tests/`). Lives under `src/`
//     so the resolver finds it under `customConditions: ['source']`.
//   - `dist/native-bootstrap.js` — raw IIFE the host passes as the plugin's
//     `initScript` arg (a Rust crate may also `include_str!` it).
//
// Both outputs are gitignored and produced fresh on every `vp install` via the
// package's `prepare` script.

import { mkdirSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { build } from 'esbuild'

// `import.meta.dirname` is a string by spec (Node 20.11+).
const pkgRoot = resolve(import.meta.dirname, '..')

const result = await build({
  entryPoints: [resolve(pkgRoot, 'src/native-sniffer-entry.ts')],
  bundle: true,
  format: 'iife',
  platform: 'browser',
  target: 'es2020',
  write: false,
  legalComments: 'none',
  minify: false,
  // Match the TS infra's `customConditions: ['source']`: workspace packages
  // export `./src/index.ts` under the `source` condition so consumers compile
  // from source without an intermediate build step.
  conditions: ['source'],
})

const code = result.outputFiles[0].text.trim()

const generatedTs = `// @generated by scripts/build-native-bootstrap.mts — do not edit by hand.
// Regenerate with \`vp run generate-native-bootstrap\` after changing
// native-sniffer-entry.ts or any of its transitive imports (install-sniffer,
// native-bridge). Gitignored — produced fresh on every \`vp install\` via the
// package's \`prepare\` script.

const nativeSnifferBootstrapScript: string = ${JSON.stringify(code)}

export { nativeSnifferBootstrapScript }
`

const tsOutPath = resolve(pkgRoot, 'src/native-bootstrap.generated.ts')
writeFileSync(tsOutPath, generatedTs, 'utf8')

const distDir = resolve(pkgRoot, 'dist')
mkdirSync(distDir, { recursive: true })
const jsOutPath = resolve(distDir, 'native-bootstrap.js')
writeFileSync(jsOutPath, code, 'utf8')

// oxlint-disable-next-line no-console -- intentional build-step output
console.log(`Wrote ${tsOutPath} and ${jsOutPath} (${code.length} chars)`)
