import { createRouter } from '@tanstack/react-router'
import { describe, expect, test } from 'vite-plus/test'

import { authSubtree, openSubtree, settingsSubtree } from '../src/route-handles.ts'
import { routeTree } from '../src/routeTree.gen.ts'

// `route-handles.ts` re-exports bare `createFileRoute(...)` objects whose
// `fullPath`/`id` stay undefined until the route tree is initialised.
// Building a router from the generated tree runs that init in place on the
// very objects route-handles re-exports, so `Route.fullPath` reads below.
// (`routeTree.gen.ts` is generated by the TanStack router plugin, which runs
// as part of `vp test`.)
// oxlint-disable-next-line typescript/no-unsafe-assignment -- `routeTree.gen.ts` carries `@ts-nocheck` (TanStack mandates excluding it from type-checking), so oxlint resolves its `routeTree` export to an error type and flags this otherwise-safe assignment
const router = createRouter({ routeTree })

describe('tunnel route-handles', () => {
  test('the settings bucket declares exactly one route at /settings/tunnel/', () => {
    expect(settingsSubtree.length).toBe(1)
    // The screen is an index route, so the resolved fullPath keeps the
    // trailing slash.
    expect(settingsSubtree[0]?.fullPath).toBe('/settings/tunnel/')
  })

  test('tunnel contributes no open or authenticated routes', () => {
    expect(openSubtree).toEqual([])
    expect(authSubtree).toEqual([])
  })

  test('the generated tree exposes exactly the tunnel settings route', () => {
    const ids = Object.keys(router.routesById).filter((id) => id !== '__root__')
    expect(ids).toEqual(['/settings/tunnel/'])
  })
})
