//! Host-side serving of the vendored patient-browser SPA.
//!
//! The Rust counterpart to the TS `vendor-apps` HttpApi group: rather than
//! decode one combined base64 module at runtime, this crate embeds the upstream
//! `dist/` as **individual files** at build time (see `build.rs`) and serves
//! each one directly under `/installed-apps/patient-browser/`, with the same
//! content types and cache policy the TS handler uses.
//!
//! [`setup_vendor_apps`] returns a plain [`axum::Router`] the host merges into
//! its public (unauthenticated) surface — the launch redirect
//! (`GET /apps/patient-browser` → `…/installed-apps/patient-browser/index.html`)
//! lands here. The crate has no Tauri/GTK dependency, so it compiles in the main
//! Rust CI; only the host that mounts it pulls in Tauri.
//!
//! When the vendored dist is absent at build time the embedded table is empty
//! and every route 404s — a fresh clone or CI compiles fine, the assets just
//! aren't there until someone runs the upstream build (see vendor-apps/README).

use std::collections::HashMap;
use std::sync::Arc;

use axum::body::{Body, Bytes};
use axum::extract::{Path, State};
use axum::http::{header, StatusCode};
use axum::response::Response;
use axum::routing::get;
use axum::Router;

/// Mount prefix the patient-browser assets are served under. Trailing slash
/// included: the catch-all route is `"{PREFIX}{*path}"` and the bare
/// trailing-slash request maps to `index.html`.
const PREFIX: &str = "/installed-apps/patient-browser/";

/// Fingerprinted bundles (`assets/`, `img/`, fonts) never change for a given
/// build, so they cache for a year. `index.html` and `config/*` are the
/// rotation points a redeploy can repoint, so they stay short-lived with
/// revalidation. Mirrors the TS handler's policy verbatim.
const IMMUTABLE_CACHE_CONTROL: &str = "public, max-age=31536000, immutable";
const SHORT_CACHE_CONTROL: &str = "public, max-age=60, must-revalidate";

/// One embedded asset: its mount-relative path (the lookup key), its content
/// type, and its bytes. Public because the `build.rs`-generated table
/// constructs these literals.
pub struct Asset {
    pub path: &'static str,
    pub content_type: &'static str,
    pub bytes: &'static [u8],
}

// `pub static ASSETS: &[Asset] = &[ … ];` — generated by build.rs. Empty when
// the vendored dist was absent at build time.
include!(concat!(env!("OUT_DIR"), "/assets.rs"));

/// Path → asset index, built once per router from the embedded slice.
type AssetMap = HashMap<&'static str, &'static Asset>;

/// Router serving the embedded patient-browser assets under [`PREFIX`].
/// Merge it into the host's public router.
pub fn setup_vendor_apps() -> Router {
    build_router(ASSETS)
}

/// Inner constructor over an explicit asset slice, so tests can drive the
/// routing/headers logic against a synthetic table without depending on a
/// populated vendor dist.
fn build_router(assets: &'static [Asset]) -> Router {
    let map: Arc<AssetMap> = Arc::new(assets.iter().map(|asset| (asset.path, asset)).collect());
    Router::new()
        // Catch-all under the mount: `assets/app.js`, `config/default.json5`, …
        .route(&format!("{PREFIX}{{*path}}"), get(serve_asset))
        // Bare trailing-slash mount → index.html.
        .route(PREFIX, get(serve_index))
        .with_state(map)
}

async fn serve_index(State(map): State<Arc<AssetMap>>) -> Response {
    respond(&map, "")
}

async fn serve_asset(State(map): State<Arc<AssetMap>>, Path(path): Path<String>) -> Response {
    respond(&map, &path)
}

/// Look the (normalized) path up and respond with the asset bytes + headers, or
/// a plain-text 404.
fn respond(map: &AssetMap, rel: &str) -> Response {
    let normalized = normalize_rel(rel);
    match map.get(normalized.as_str()) {
        Some(asset) => Response::builder()
            .status(StatusCode::OK)
            .header(header::CONTENT_TYPE, asset.content_type)
            .header(header::CACHE_CONTROL, cache_control_for(&normalized))
            // `from_static` is zero-copy over the embedded bytes.
            .body(Body::from(Bytes::from_static(asset.bytes)))
            .expect("asset response builds from validated header values"),
        None => Response::builder()
            .status(StatusCode::NOT_FOUND)
            .header(header::CONTENT_TYPE, "text/plain; charset=utf-8")
            .body(Body::from("Not found"))
            .expect("404 response builds from constant header values"),
    }
}

/// Map a mount-relative request path to an asset key: an empty path or one
/// ending in `/` resolves to that directory's `index.html` (only the SPA root
/// ships one today). Mirrors the TS `lookupAsset` normalization.
fn normalize_rel(rel: &str) -> String {
    if rel.is_empty() || rel.ends_with('/') {
        format!("{rel}index.html")
    } else {
        rel.to_owned()
    }
}

/// Cache-Control for a normalized asset key (see the cache constants).
fn cache_control_for(rel: &str) -> &'static str {
    if rel == "index.html" || rel.starts_with("config/") {
        SHORT_CACHE_CONTROL
    } else {
        IMMUTABLE_CACHE_CONTROL
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use axum::body::to_bytes;
    use axum::http::Request;
    use tower::ServiceExt;

    static INDEX_HTML: &[u8] = b"<!doctype html><title>patient-browser</title>";
    static APP_JS: &[u8] = b"console.log('patient-browser')";
    static DEFAULT_CONFIG: &[u8] = b"{ url: \"/fhir-r4\" }";

    // A synthetic stand-in for the embedded dist so the routing + header policy
    // is exercised without a populated vendor build.
    static TEST_ASSETS: &[Asset] = &[
        Asset {
            path: "index.html",
            content_type: "text/html; charset=utf-8",
            bytes: INDEX_HTML,
        },
        Asset {
            path: "assets/app.js",
            content_type: "application/javascript; charset=utf-8",
            bytes: APP_JS,
        },
        Asset {
            path: "config/default.json5",
            content_type: "application/json; charset=utf-8",
            bytes: DEFAULT_CONFIG,
        },
    ];

    async fn get(path: &str) -> Response {
        build_router(TEST_ASSETS)
            .oneshot(
                Request::get(path)
                    .body(Body::empty())
                    .expect("request builds"),
            )
            .await
            .expect("router is infallible")
    }

    fn header(res: &Response, name: header::HeaderName) -> String {
        res.headers()
            .get(name)
            .expect("header present")
            .to_str()
            .expect("header is ascii")
            .to_owned()
    }

    #[tokio::test]
    async fn serves_index_html_with_short_cache() {
        let res = get("/installed-apps/patient-browser/index.html").await;
        assert_eq!(res.status(), StatusCode::OK);
        assert_eq!(
            header(&res, header::CONTENT_TYPE),
            "text/html; charset=utf-8"
        );
        assert_eq!(header(&res, header::CACHE_CONTROL), SHORT_CACHE_CONTROL);
        let body = to_bytes(res.into_body(), usize::MAX).await.unwrap();
        assert_eq!(body.as_ref(), INDEX_HTML);
    }

    #[tokio::test]
    async fn trailing_slash_mount_serves_index() {
        let res = get("/installed-apps/patient-browser/").await;
        assert_eq!(res.status(), StatusCode::OK);
        assert_eq!(
            header(&res, header::CONTENT_TYPE),
            "text/html; charset=utf-8"
        );
        let body = to_bytes(res.into_body(), usize::MAX).await.unwrap();
        assert_eq!(body.as_ref(), INDEX_HTML);
    }

    #[tokio::test]
    async fn fingerprinted_asset_is_immutable() {
        let res = get("/installed-apps/patient-browser/assets/app.js").await;
        assert_eq!(res.status(), StatusCode::OK);
        assert_eq!(
            header(&res, header::CONTENT_TYPE),
            "application/javascript; charset=utf-8"
        );
        assert_eq!(header(&res, header::CACHE_CONTROL), IMMUTABLE_CACHE_CONTROL);
    }

    #[tokio::test]
    async fn config_is_short_cache() {
        let res = get("/installed-apps/patient-browser/config/default.json5").await;
        assert_eq!(res.status(), StatusCode::OK);
        assert_eq!(header(&res, header::CACHE_CONTROL), SHORT_CACHE_CONTROL);
    }

    #[tokio::test]
    async fn unknown_asset_is_404() {
        let res = get("/installed-apps/patient-browser/does-not-exist.js").await;
        assert_eq!(res.status(), StatusCode::NOT_FOUND);
    }

    #[test]
    fn normalize_rel_maps_empty_and_dir_to_index() {
        assert_eq!(normalize_rel(""), "index.html");
        assert_eq!(normalize_rel("config/"), "config/index.html");
        assert_eq!(normalize_rel("assets/app.js"), "assets/app.js");
    }

    #[test]
    fn cache_control_policy() {
        assert_eq!(cache_control_for("index.html"), SHORT_CACHE_CONTROL);
        assert_eq!(
            cache_control_for("config/default.json5"),
            SHORT_CACHE_CONTROL
        );
        assert_eq!(cache_control_for("assets/app.js"), IMMUTABLE_CACHE_CONTROL);
    }
}
