//! Embedded sniffer bootstrap IIFE.
//!
//! The TypeScript build step in `browser-sniffer-tauri` writes the
//! self-contained IIFE bundle to `dist/tauri-bootstrap.js` (gitignored
//! — regenerated by `pnpm install` locally and by CI's tauri job
//! before `cargo build`). We pull it in via `include_str!` so the Rust
//! crate ships a frozen snapshot at compile time — no runtime fetch,
//! no filesystem lookup at process start, no path management for the
//! host `.app` bundle.
//!
//! Drift between the TS source (`tauri-sniffer-entry.ts`) and the
//! embedded file is caught two ways: the `bootstrap_is_non_empty` test
//! in `lib.rs` fails on a missing-or-stubbed build, and the integration
//! tests in `browser-sniffer-tauri/tests/bootstrap.test.ts` round-trip
//! the same bytes through jsdom.

pub(crate) const SNIFFER_BOOTSTRAP: &str =
    include_str!("../../browser-sniffer-tauri/dist/tauri-bootstrap.js");
