if [ -n "$GIT_NAME" ]; then
  git config --global user.name "$GIT_NAME"
fi
if [ -n "$GIT_EMAIL" ]; then
  git config --global user.email "$GIT_EMAIL"
fi
gh auth setup-git
sudo chown -R $(whoami) /workspaces/wildflower/node_modules

# /data layout (persistent across rebuilds) — see CLAUDE.md "Parallel Worktrees".
sudo mkdir -p /data/pnpm-store /data/pnpm-cache /data/pnpm-global /data/worktrees /data/cargo-target/main
sudo chown -R "$(whoami)" /data
pnpm config set store-dir /data/pnpm-store
pnpm config set cache-dir /data/pnpm-cache

# Redirect Cargo's incremental output onto the wf-data volume for the same
# reason the pnpm store/cache are redirected above: keep the thousands of
# small files cargo writes off the slow macOS↔Linux bind mount. The .cargo/
# directory is gitignored. Worktrees get their own subdir under
# /data/cargo-target/worktrees/<branch> via wf-worktree.sh.
mkdir -p /workspaces/wildflower/.cargo
cat > /workspaces/wildflower/.cargo/config.toml <<'CARGO_CONFIG_EOF'
# Generated by .devcontainer/postCreateCommand.sh — do not commit.
[build]
target-dir = "/data/cargo-target/main"
CARGO_CONFIG_EOF

# Set PNPM_HOME explicitly: `pnpm setup` does not reliably write to ~/.bashrc
# when the file already has a custom prompt block, which left vp unreachable.
export PNPM_HOME=/data/pnpm-global
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
if ! grep -q 'PNPM_HOME=/data/pnpm-global' ~/.bashrc; then
  cat >> ~/.bashrc <<'BASHRC_EOF'

export PNPM_HOME=/data/pnpm-global
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
BASHRC_EOF
fi

# Pin every global to the version the workspace resolves so the bootstrap vp
# matches the workspace-local vp — unpinned, `vite-plus` drifts to newer
# releases and its bundled vitest peer-warns against the aliased vite. These
# pins must be re-synced on every bump; the full list of places a vite-plus
# version is recorded is in docs/Dependencies/Bumping vite-plus How-To.md.
pnpm install -g vite-plus@0.3.2
pnpm install -g @typescript/native-preview@7.0.0-dev.20260707.2
pnpm install -g @tsdown/css@0.23.0
vp install


echo 'alias danger-claude="claude --dangerously-skip-permissions"' >> ~/.bashrc