plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'expo.modules.effectplatform'
version = '0.1.0'

android {
  namespace "expo.modules.effectplatform"
  defaultConfig {
    versionCode 1
    versionName "0.1.0"
  }
  lintOptions {
    abortOnError false
  }
}

dependencies {
  implementation 'io.ktor:ktor-server-core:3.0.3'
  implementation 'io.ktor:ktor-server-cio:3.0.3'
}
