import { createRouter, type AnyRoute } from '@tanstack/react-router'
import { describe, expect, test } from 'vite-plus/test'

import { authSubtree, openSubtree, settingsSubtree } from '../src/route-handles.ts'
import { routeTree } from '../src/routeTree.gen.ts'

// `route-handles.ts` re-exports the bare `createFileRoute(...)` objects,
// whose `fullPath`/`id` stay undefined until the route tree is initialised.
// Building a router from the generated tree runs that init in place on the
// very objects route-handles re-exports, so `Route.fullPath` reads below.
// (`routeTree.gen.ts` is generated by the TanStack router plugin, which runs
// as part of `vp test`.)
// oxlint-disable-next-line typescript/no-unsafe-assignment -- `routeTree.gen.ts` carries `@ts-nocheck` (TanStack mandates excluding it from type-checking), so oxlint resolves its `routeTree` export to an error type and flags this otherwise-safe assignment
const router = createRouter({ routeTree })

const fullPaths = (routes: readonly AnyRoute[]): readonly string[] =>
  routes.map((route) => route.fullPath)

describe('collector route-handles', () => {
  test('every authenticated route is under /collector', () => {
    for (const path of fullPaths(authSubtree)) {
      expect(path.startsWith('/collector')).toBe(true)
    }
  })

  test('no authenticated route is under /settings — collector is top-level, not a settings concern', () => {
    for (const path of fullPaths(authSubtree)) {
      expect(path.startsWith('/settings')).toBe(false)
    }
  })

  test('collector contributes only authenticated routes', () => {
    // The open and settings buckets are intentionally empty; a route landing
    // in one should be a deliberate edit, not a silent drift.
    expect(openSubtree).toEqual([])
    expect(settingsSubtree).toEqual([])
  })

  test('the generated tree exposes exactly the collector routes', () => {
    const ids = Object.keys(router.routesById)
      .filter((id) => id !== '__root__')
      .toSorted()
    expect(ids).toEqual(['/collector/', '/collector/account/$id', '/collector/account/new'])
  })
})
