import { createRouter, type AnyRoute } from '@tanstack/react-router'
import { GatekeeperPaths } from 'gatekeeper-core/page-paths'
import { describe, expect, test } from 'vite-plus/test'

import { authSubtree, openSubtree, settingsSubtree } from '../src/route-handles.ts'
import { routeTree } from '../src/routeTree.gen.ts'

// `route-handles.ts` re-exports the bare `createFileRoute(...)` objects,
// whose `fullPath`/`id` stay undefined until the route tree is initialised.
// Building a router from the generated tree runs that init in place on the
// very objects route-handles re-exports, so `Route.fullPath` reads below.
// (`routeTree.gen.ts` is generated by the TanStack router plugin, which runs
// as part of `vp test`.)
const router = createRouter({ routeTree })

const fullPaths = (routes: readonly AnyRoute[]): readonly string[] =>
  routes.map((route) => route.fullPath)

// GatekeeperPaths percent-encodes its params; decode so `$id` / `$userCode`
// line up with the `createFileRoute` literals TanStack resolves to.
const oauthPolling = decodeURIComponent(GatekeeperPaths.oauthPollingPath('$id'))
const oauthConsent = decodeURIComponent(GatekeeperPaths.oauthConsentPath('$id'))
const deviceEntry = decodeURIComponent(GatekeeperPaths.deviceEntryPath())
const deviceConsent = decodeURIComponent(GatekeeperPaths.deviceConsentPath('$userCode'))

describe('GatekeeperPaths ↔ Route.fullPath drift', () => {
  // One-direction drift only: owner-facing settings routes are intentionally
  // absent from `GatekeeperPaths`.
  test('every GatekeeperPaths redirect target has a matching route', () => {
    const external = [...fullPaths(openSubtree), ...fullPaths(authSubtree)]
    for (const target of [oauthPolling, oauthConsent, deviceEntry, deviceConsent]) {
      expect(external).toContain(target)
    }
  })

  // oauth-polling and device-entry are reachable without a bearer: the
  // polling endpoint is unauth, and device-entry is where an owner types a
  // code from another device.
  test('oauth-polling and device-entry live in the open bucket', () => {
    const open = fullPaths(openSubtree)
    expect(open).toContain(oauthPolling)
    expect(open).toContain(deviceEntry)
  })

  // oauth-consent and device-consent require the owner to already be
  // authenticated.
  test('oauth-consent and device-consent live in the authenticated bucket', () => {
    const auth = fullPaths(authSubtree)
    expect(auth).toContain(oauthConsent)
    expect(auth).toContain(deviceConsent)
  })

  // GatekeeperPaths models only externally-published URLs; owner-facing
  // settings landings must never appear there.
  test('settings landings are not externally published', () => {
    const external = [...fullPaths(openSubtree), ...fullPaths(authSubtree)]
    for (const path of fullPaths(settingsSubtree)) {
      expect(external).not.toContain(path)
    }
  })
})

describe('gatekeeper settings bucket', () => {
  test('every settings route is under /settings/gatekeeper', () => {
    for (const path of fullPaths(settingsSubtree)) {
      expect(path === '/settings/gatekeeper/' || path.startsWith('/settings/gatekeeper/')).toBe(
        true
      )
    }
  })

  test('declares the four owner-facing landing routes', () => {
    expect([...fullPaths(settingsSubtree)].toSorted()).toEqual(
      [
        '/settings/gatekeeper/',
        '/settings/gatekeeper/approved/$id',
        '/settings/gatekeeper/requests',
        '/settings/gatekeeper/requests/$id',
      ].toSorted()
    )
  })
})

describe('gatekeeper route tree', () => {
  test('the generated tree exposes exactly the documented routes', () => {
    const ids = Object.keys(router.routesById)
      .filter((id) => id !== '__root__')
      .toSorted()
    expect(ids).toEqual(
      [
        '/gatekeeper/devices',
        '/gatekeeper/devices/$userCode',
        '/gatekeeper/oauth-consent/$id',
        '/gatekeeper/oauth-polling/$id',
        '/settings/gatekeeper/',
        '/settings/gatekeeper/approved/$id',
        '/settings/gatekeeper/requests',
        '/settings/gatekeeper/requests/$id',
      ].toSorted()
    )
  })
})
