import { type HttpApiGroup, HttpApiBuilder } from '@effect/platform'
import type { Layer } from 'effect'
import { Effect } from 'effect'
import { GatekeeperApi } from 'gatekeeper-core/http-api-definition'
import { html as spaHtml } from 'gatekeeper-web/html'

// SPA-shell pages share the prebuilt single-file bundle from
// `gatekeeper-web/html`; the only per-route variation is the injected
// `__INITIAL_ROUTE__` so MemoryRouter starts on the right screen.
const HEAD_OPEN_TAG = /<head(\s[^>]*)?>/i

const renderSpaShell = (route: string): string => {
  const injection = `<script>window.__INITIAL_ROUTE__=${JSON.stringify(route)};</script>`
  const match = HEAD_OPEN_TAG.exec(spaHtml)
  if (match === null) {
    // The bundle is generated by our own build; a missing `<head>` is a
    // build invariant violation, not a runtime fallback case.
    throw new Error('gatekeeper-web SPA bundle missing <head> tag')
  }
  const insertAt = match.index + match[0].length
  return spaHtml.slice(0, insertAt) + injection + spaHtml.slice(insertAt)
}

const oauthPollingRoute = (id: string): string => `/oauth-polling/${encodeURIComponent(id)}`
const oauthConsentRoute = (id: string): string => `/oauth-consent/${encodeURIComponent(id)}`
const deviceConsentRoute = (userCode: string): string => `/devices/${encodeURIComponent(userCode)}`

// Phantom-id bridge: see gatekeeper-core's GatekeeperApiHandlersFor for the
// canonical long-form explanation. A Layer built against GatekeeperApi
// satisfies a parent ApiId's group requirement because
// `ApiGroup<ApiId, Name>` is a structural marker with no runtime presence.
type GatekeeperWebGroupNames = 'gatekeeper-pages'

const GatekeeperPagesHandlersLive = HttpApiBuilder.group(
  GatekeeperApi,
  'gatekeeper-pages',
  (handlers) =>
    handlers
      .handle('OAuthPollingPage', ({ path: { id } }) =>
        Effect.succeed(renderSpaShell(oauthPollingRoute(id)))
      )
      .handle('OAuthConsentPage', ({ path: { id } }) =>
        Effect.succeed(renderSpaShell(oauthConsentRoute(id)))
      )
      .handle('DeviceEntryPage', () => Effect.succeed(renderSpaShell('/devices')))
      .handle('DeviceConsentPage', ({ path: { userCode } }) =>
        Effect.succeed(renderSpaShell(deviceConsentRoute(userCode)))
      )
) satisfies Layer.Layer<
  HttpApiGroup.ApiGroup<'GatekeeperApi', GatekeeperWebGroupNames>,
  never,
  never
>

const GatekeeperPagesHandlersFor = <ParentId extends string>(): Layer.Layer<
  HttpApiGroup.ApiGroup<ParentId, GatekeeperWebGroupNames>,
  never,
  never
> =>
  // oxlint-disable-next-line typescript/no-unsafe-type-assertion
  GatekeeperPagesHandlersLive satisfies Layer.Layer<
    HttpApiGroup.ApiGroup<'GatekeeperApi', GatekeeperWebGroupNames>,
    never,
    never
  > as unknown as Layer.Layer<
    HttpApiGroup.ApiGroup<ParentId, GatekeeperWebGroupNames>,
    never,
    never
  >

export { GatekeeperPagesHandlersFor, GatekeeperPagesHandlersLive }
