import { DateTime, Schema } from 'effect'
import { describe, expect, test } from 'vite-plus/test'

import * as Extension from './extension.ts'

// Use decodeUnknown since we're constructing raw wire-format objects
const decode = Schema.decodeSync(Extension.Schema)

describe('Extension', () => {
  test('ResourceType static equals "Extension"', () => {
    expect(Extension.ResourceType).toBe('Extension')
  })

  test('self-recursive: decodes nested extensions preserving value', () => {
    const ext = decode({
      id: null,
      url: 'http://outer',
      extension: [
        {
          id: null,
          url: 'http://inner',
          valueInteger: 42,
          extension: [],
          valueAddress: null,
          valueAge: null,
          valueAnnotation: null,
          valueAttachment: null,
          valueCodeableConcept: null,
          valueCoding: null,
          valueContactPoint: null,
          valueCount: null,
          valueDistance: null,
          valueDuration: null,
          valueHumanName: null,
          valueIdentifier: null,
          valueMoney: null,
          valuePeriod: null,
          valueQuantity: null,
          valueRange: null,
          valueRatio: null,
          valueReference: null,
          valueSampledData: null,
          valueSignature: null,
          valueSimpleQuantity: null,
          valueTiming: null,
          valueMetaDataTypes: null,
          valueContactDetail: null,
          valueContributor: null,
          valueDataRequirement: null,
          valueExpression: null,
          valueParameterDefinition: null,
          valueRelatedArtifact: null,
          valueTriggerDefinition: null,
          valueUsageContext: null,
          valueDosage: null,
          valueMeta: null,
          valueString: null,
          valueBoolean: null,
          valueBase64Binary: null,
          valueCanonical: null,
          valueCode: null,
          valueDate: null,
          valueDateTime: null,
          valueDecimal: null,
          valueId: null,
          valueInstant: null,
          valueMarkdown: null,
          valueOid: null,
          valuePositiveInt: null,
          valueTime: null,
          valueUnsignedInt: null,
          valueUri: null,
          valueUrl: null,
          valueUuid: null,
        },
      ],
      valueString: 'outer-value',
      valueAddress: null,
      valueAge: null,
      valueAnnotation: null,
      valueAttachment: null,
      valueCodeableConcept: null,
      valueCoding: null,
      valueContactPoint: null,
      valueCount: null,
      valueDistance: null,
      valueDuration: null,
      valueHumanName: null,
      valueIdentifier: null,
      valueMoney: null,
      valuePeriod: null,
      valueQuantity: null,
      valueRange: null,
      valueRatio: null,
      valueReference: null,
      valueSampledData: null,
      valueSignature: null,
      valueSimpleQuantity: null,
      valueTiming: null,
      valueMetaDataTypes: null,
      valueContactDetail: null,
      valueContributor: null,
      valueDataRequirement: null,
      valueExpression: null,
      valueParameterDefinition: null,
      valueRelatedArtifact: null,
      valueTriggerDefinition: null,
      valueUsageContext: null,
      valueDosage: null,
      valueMeta: null,
      valueBoolean: null,
      valueId: null,
      valueBase64Binary: null,
      valueCanonical: null,
      valueCode: null,
      valueDate: null,
      valueDateTime: null,
      valueDecimal: null,
      valueInstant: null,
      valueInteger: null,
      valueMarkdown: null,
      valueOid: null,
      valuePositiveInt: null,
      valueTime: null,
      valueUnsignedInt: null,
      valueUri: null,
      valueUrl: null,
      valueUuid: null,
    })

    expect(ext.extension).toHaveLength(1)
    expect(ext.extension[0]?.url).toBe('http://inner')

    expect(ext.extension[0]?.valueInteger).toBe(42)
  })

  test('round-trip encode/decode preserves value', () => {
    const encode = Schema.encodeSync(Extension.Schema)
    const input = decode({
      url: 'http://test',
      valueDateTime: '2024-01-01T00:00:00Z',
      id: null,
      extension: [],
      valueInteger: null,
      valueAddress: null,
      valueAge: null,
      valueAnnotation: null,
      valueAttachment: null,
      valueCodeableConcept: null,
      valueCoding: null,
      valueContactPoint: null,
      valueCount: null,
      valueDistance: null,
      valueDuration: null,
      valueHumanName: null,
      valueIdentifier: null,
      valueMoney: null,
      valuePeriod: null,
      valueQuantity: null,
      valueRange: null,
      valueRatio: null,
      valueReference: null,
      valueSampledData: null,
      valueSignature: null,
      valueSimpleQuantity: null,
      valueTiming: null,
      valueMetaDataTypes: null,
      valueContactDetail: null,
      valueContributor: null,
      valueDataRequirement: null,
      valueExpression: null,
      valueParameterDefinition: null,
      valueRelatedArtifact: null,
      valueTriggerDefinition: null,
      valueUsageContext: null,
      valueDosage: null,
      valueMeta: null,
      valueString: null,
      valueBoolean: null,
      valueUrl: null,
      valueBase64Binary: null,
      valueCanonical: null,
      valueCode: null,
      valueDate: null,
      valueDecimal: null,
      valueId: null,
      valueInstant: null,
      valueMarkdown: null,
      valueOid: null,
      valuePositiveInt: null,
      valueTime: null,
      valueUnsignedInt: null,
      valueUri: null,
      valueUuid: null,
    })
    const encoded = encode(input)
    const reDecoded = decode(encoded)
    expect(reDecoded.valueDateTime).toEqual(DateTime.unsafeMake('2024-01-01T00:00:00Z'))
  })
})
