// Build-time bundler for the sandboxed-webview bootstrap.
//
// Bundles `src/sandboxed-webview-entry.ts` (the `__TAURI__` lookup +
// `injectBrowserTopBar(...)` invocation) as a self-contained IIFE. Writes the
// result to two paths:
//   - `src/tauri-bootstrap.generated.ts` — `string` constant for the TypeScript
//     exports in `src/index.ts` (and the tests in `src/`). Lives under `src/`
//     so the TS module resolver finds it under `customConditions: ['source']`.
//   - `dist/tauri-bootstrap.js` — raw IIFE the Rust crate
//     `shared-structures-tauri-rust` includes via `include_str!`.
//
// Both outputs are gitignored. CI's `tauri` lint/test job runs `pnpm install`
// (which triggers this script via `prepare`) before `cargo build`, so the
// latest bytes are always compiled in. Rust-only PRs that don't touch this
// bootstrap fall back to a stub written by the workflow so `include_str!`
// resolves at compile time. Mirrors browser-sniffer-tauri's build script.

import { mkdirSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { build } from 'esbuild'

// `import.meta.dirname` is a string by spec (Node 20.11+).
const pkgRoot = resolve(import.meta.dirname, '..')

const result = await build({
  entryPoints: [resolve(pkgRoot, 'src/sandboxed-webview-entry.ts')],
  bundle: true,
  format: 'iife',
  platform: 'browser',
  target: 'es2020',
  write: false,
  legalComments: 'none',
  minify: false,
  // Match the TS infra's `customConditions: ['source']`: workspace packages
  // export `./src/*.ts` under the `source` condition so consumers compile from
  // source without an intermediate build step.
  conditions: ['source'],
})

const code = result.outputFiles[0].text.trim()

const generatedTs = `// @generated by scripts/build-tauri-bootstrap.mts — do not edit by hand.
// Regenerate with \`vp run generate-tauri-bootstrap\` after changing
// sandboxed-webview-entry.ts or any of its transitive imports (including the
// shared top bar in inject-browser-top-bar.ts). Gitignored — produced fresh on
// every \`vp install\` via the package's \`prepare\` script.

const sandboxedWebViewBootstrapScript: string = ${JSON.stringify(code)}

export { sandboxedWebViewBootstrapScript }
`

const tsOutPath = resolve(pkgRoot, 'src/tauri-bootstrap.generated.ts')
writeFileSync(tsOutPath, generatedTs, 'utf8')

const distDir = resolve(pkgRoot, 'dist')
mkdirSync(distDir, { recursive: true })
const jsOutPath = resolve(distDir, 'tauri-bootstrap.js')
writeFileSync(jsOutPath, code, 'utf8')

// oxlint-disable-next-line no-console -- intentional build-step output
console.log(`Wrote ${tsOutPath} and ${jsOutPath} (${code.length} chars)`)
