//! Embedded sandboxed-webview bootstrap IIFE.
//!
//! The TypeScript build step in `shared-structures-tauri` writes the
//! self-contained IIFE bundle to `dist/tauri-bootstrap.js` (gitignored —
//! regenerated by `pnpm install` locally and by CI's tauri job before
//! `cargo build`). We pull it in via `include_str!` so the Rust crate ships a
//! frozen snapshot at compile time — no runtime fetch, no filesystem lookup at
//! process start.
//!
//! The bundle injects the shared in-page browser top bar (Back / Reload / URL)
//! configured for the sandboxed webview: its Back-with-empty-history / Close
//! action emits `CloseSandboxedWebView` on the multiplexed bridge channel, which
//! [`crate::sandboxed_webview::attach_close_listener`] turns into a window close.
//!
//! Drift between the TS source (`sandboxed-webview-entry.ts`) and the embedded
//! file is caught by the `bootstrap_is_non_empty` test in
//! [`crate::sandboxed_webview`], which fails on a missing-or-stubbed build.

pub(crate) const SANDBOXED_WEBVIEW_BOOTSTRAP: &str =
    include_str!("../../shared-structures-tauri/dist/tauri-bootstrap.js");
