/**
 * The document transforms that turn a committed OpenAPI snapshot into something
 * the console can actually send requests with.
 *
 * The snapshots are generated by each slice's Rust crate for drift-guarding, so
 * they describe paths only: no `servers` (the host answers on whatever origin
 * the request arrived at) and no security schemes (the host gates the whole
 * admin surface in a layer, not per-operation). Both are supplied here, at
 * render time, because both are properties of the *reader's* server rather than
 * of the API definition.
 *
 * Pure data-in/data-out; the render wiring lives in `main.ts`.
 */

/**
 * An OpenAPI document as read from a committed snapshot. Deliberately untyped
 * beyond "JSON object": these transforms only add root keys, and modelling the
 * whole of OpenAPI here would buy nothing.
 */
type OpenApiDocument = Readonly<Record<string, unknown>>

/**
 * The name of the security scheme {@link withBearerAuth} injects. Matches
 * nothing in the snapshots — it exists only so the reference UI renders a token
 * field.
 */
const BEARER_SCHEME_NAME = 'bearerAuth'

/** Whether `value` is a plain JSON object (and so safe to spread as one). */
const isRecord = (value: unknown): value is Readonly<Record<string, unknown>> =>
  typeof value === 'object' && value !== null && !Array.isArray(value)

/**
 * `spec` with its server list replaced by the single `serverUrl`, so every
 * operation's "try it" request goes to the server the reader chose.
 */
const withServer = (spec: OpenApiDocument, serverUrl: string): OpenApiDocument => ({
  ...spec,
  servers: [{ url: serverUrl }],
})

/**
 * `spec` with an HTTP bearer security scheme declared and required by default.
 *
 * The running host gates its admin surface on a bearer token for any caller
 * that is not the loopback owner, but the snapshots carry no security metadata
 * to say so. Declaring it here is what makes the reference UI offer a token
 * field, so a reader with a token can send a request that is actually
 * authorised. Any scheme the snapshot already declares is preserved.
 */
const withBearerAuth = (spec: OpenApiDocument): OpenApiDocument => {
  const components = isRecord(spec.components) ? spec.components : {}
  const securitySchemes = isRecord(components.securitySchemes) ? components.securitySchemes : {}

  return {
    ...spec,
    components: {
      ...components,
      securitySchemes: {
        ...securitySchemes,
        [BEARER_SCHEME_NAME]: {
          type: 'http',
          scheme: 'bearer',
          description:
            'The access token the host issues. Loopback callers on the device are ' +
            'trusted without one; every forwarded caller needs it. Signing in from ' +
            'the header bar fills this field with a freshly issued token.',
        },
      },
    },
    security: [{ [BEARER_SCHEME_NAME]: [] }],
  }
}

/**
 * A snapshot made sendable: pointed at `serverUrl` and offering a bearer token
 * field. Composition of {@link withServer} and {@link withBearerAuth}.
 */
const preparedSpec = (spec: OpenApiDocument, serverUrl: string): OpenApiDocument =>
  withBearerAuth(withServer(spec, serverUrl))

export { BEARER_SCHEME_NAME, preparedSpec, withBearerAuth, withServer, type OpenApiDocument }
