import { Schema } from 'effect'
import { normalizeName } from 'medication-matching-core'

import { nonDrugNames } from './non-drug.ts'
import { type Severity, SeverityCode, severityFromCode } from './severity.ts'

/** Where the bundled interaction data came from, for attribution in the UI and docs. */
const DdinterSource = Schema.Struct({
  /** Database name (`"DDInter"`). */
  name: Schema.String,
  /** Database home page. */
  url: Schema.String,
  /** ISO date the download files were fetched, if recorded. */
  retrievedOn: Schema.optional(Schema.String),
  /** Free-text licence / terms note, if recorded. */
  license: Schema.optional(Schema.String),
})
type DdinterSource = typeof DdinterSource.Type

/** One catalog drug in the compact file: `[DDInter id, display name]`. */
const DdinterFileDrug = Schema.Tuple(Schema.String, Schema.String)

/**
 * One interacting pair in the compact file: `[indexA, indexB, severity code]`,
 * where the indexes point into `drugs` and `indexA < indexB`.
 */
const DdinterFilePair = Schema.Tuple(Schema.Int, Schema.Int, SeverityCode)

/**
 * The compact bundled DDInter file: a drug table plus a pair list of indexes
 * into it, generated by {@link buildDdinterFile} from DDInter's download CSVs.
 *
 * @remarks
 * The filter pins the structural invariants the converter guarantees — every
 * pair index is in range, ordered (`a < b`), and no unordered pair appears
 * twice — so a hand-edited or truncated file fails to decode rather than
 * silently reporting wrong interactions.
 */
const DdinterFile = Schema.Struct({
  source: DdinterSource,
  drugs: Schema.Array(DdinterFileDrug),
  pairs: Schema.Array(DdinterFilePair),
}).pipe(
  Schema.filter((file) => {
    const seen = new Set<string>()
    for (const [a, b] of file.pairs) {
      if (a < 0 || b >= file.drugs.length || a >= b)
        return `pair [${a}, ${b}] is out of range or unordered`
      const key = pairKey(a, b)
      if (seen.has(key)) return `pair [${a}, ${b}] appears more than once`
      seen.add(key)
    }
    return true
  })
)
type DdinterFile = typeof DdinterFile.Type

/** A drug in the decoded catalog, addressed by its position in the drug table. */
interface CatalogDrug {
  /** Position in the catalog's `drugs` array — the key the pair map uses. */
  readonly index: number
  /** DDInter's own identifier (e.g. `"DDInter1"`), used to build detail links. */
  readonly id: string
  /** DDInter's display name for the drug. */
  readonly name: string
  /** `true` when the name is a non-drug entry (food, alcohol, caffeine, …). */
  readonly nonDrug: boolean
}

/**
 * The decoded, query-ready interaction catalog: the drug table plus a
 * severity map over unordered index pairs. Build one with
 * {@link decodeDdinterFile}; query it with {@link severityBetween}.
 */
interface InteractionCatalog {
  readonly source: DdinterSource
  readonly drugs: readonly CatalogDrug[]
  /** Severity by {@link pairKey} of the two drug indexes. */
  readonly pairs: ReadonlyMap<string, Severity>
}

/** The pair-map key for an unordered index pair (order-insensitive). */
const pairKey = (a: number, b: number): string => (a < b ? `${a}:${b}` : `${b}:${a}`)

const nonDrugSet = new Set(nonDrugNames.map(normalizeName))

/** Whether a DDInter drug name is one of the curated non-drug entries. */
const isNonDrugName = (name: string): boolean => nonDrugSet.has(normalizeName(name))

/** Decode the compact file's already-validated shape into a queryable catalog. */
const catalogFromFile = (file: DdinterFile): InteractionCatalog => ({
  source: file.source,
  drugs: file.drugs.map(([id, name], index) => ({
    index,
    id,
    name,
    nonDrug: isNonDrugName(name),
  })),
  pairs: new Map(file.pairs.map(([a, b, code]) => [pairKey(a, b), severityFromCode(code)])),
})

/**
 * Decode the bundled compact DDInter JSON (as imported) into an
 * {@link InteractionCatalog}. Throws a `ParseError` on a malformed file — the
 * bundle is build-time data, so a bad file is a build defect, not a runtime
 * condition to recover from.
 */
const decodeDdinterFile = (raw: unknown): InteractionCatalog =>
  catalogFromFile(Schema.decodeUnknownSync(DdinterFile)(raw))

/** The interaction severity DDInter lists between two catalog drugs, or `null` if none. */
const severityBetween = (catalog: InteractionCatalog, a: number, b: number): Severity | null =>
  a === b ? null : (catalog.pairs.get(pairKey(a, b)) ?? null)

/** DDInter's home page, for attribution. */
const DDINTER_HOME_URL = 'https://ddinter.scbdd.com/'

/**
 * The DDInter detail page for a catalog drug, where its full interaction list
 * (including the pair a row reports) can be read.
 *
 * @remarks
 * The path scheme (`/ddinter/drug-detail/<DDInter id>/`) is the one place the
 * site's URL layout is assumed; it was written from memory while the host was
 * unreachable, so verify it against a live page and change it here only.
 */
const ddinterDrugUrl = (drug: CatalogDrug): string =>
  `${DDINTER_HOME_URL}ddinter/drug-detail/${encodeURIComponent(drug.id)}/`

export {
  type CatalogDrug,
  DDINTER_HOME_URL,
  ddinterDrugUrl,
  DdinterFile,
  DdinterSource,
  decodeDdinterFile,
  type InteractionCatalog,
  isNonDrugName,
  pairKey,
  severityBetween,
}
